---
# - id: circleci-config-validate
#   name: CircleCI config validation
#   description: Test if the CircleCI config is well formed.
#   entry: hooks/circleci-config-validate.sh
#   language: script
#   files: ^.circleci/config.yml$

# - id: go-fmt
#   name: go fmt
#   description: Runs `go fmt` and asserts no changes are needed.
#   entry: hooks/go-fmt.sh
#   language: script
#   files: \.go$

# - id: go-test
#   name: go test
#   description: Runs `go test` and asserts no tests are failing.
#   entry: hooks/go-test.sh
#   language: script
#   files: \.go$

# - id: go-mod-tidy
#   name: go mod tidy
#   description: Runs `go mod tidy` to ensure `go.mod` matches the project source.
#   entry: hooks/go-mod-tidy.sh
#   language: script
#   files: \.go$

# - id: go-generate
#   name: go generate
#   description: Runs `go generate` against the projects go files.
#   entry: hooks/go-generate.sh
#   language: script
#   files: \.go$
#   always_run: true

# - id: forbid-binary
#   name: Forbid binaries
#   description: Forbid binary files from being committed
#   entry: hooks/forbid-binary.sh
#   language: script
#   types: ['binary']

- id: git-check
  name: Check for conflict markers and core.whitespace errors
  description: Use Git to check for conflict markers and core.whitespace errors, respecting .gitattributes.
  language: script
  entry: hooks/git-check.sh
  require_serial: false

- id: script-must-have-extension
  name: Shell script filename ends in .sh
  description: Verifies that shell script filenames ends in .sh.
  language: script
  entry: hooks/script_must_have_extension.sh
  types:
    - shell

- id: shellcheck
  name: Test shell scripts with ShellCheck
  description: Run ShellCheck over the file to identify poor practices or potential problems.
  language: script
  entry: hooks/shellcheck.sh
  require_serial: false
  types:
    - shell
  exclude_types:
    - csh
    - perl
    - python
    - ruby
    - tcsh
    - zsh
  args:
    - -e
    - SC1091

- id: shfmt
  name: Format shell scripts with shfmt
  description: Reformat the shell scripts according to the standard format.
  language: script
  entry: hooks/shfmt.sh
  require_serial: false
  types:
    - shell
  exclude_types:
    - csh
    - perl
    - python
    - ruby
    - tcsh
    - zsh
  args:
    - -s
    - -w
    - -ln=bash
    - -i=4
    - -ci
    - -sr

- id: yamlfmt
  name: Format YAML files
  description: Format YAML files
  entry: yamlfmt
  language: python
  types:
    - yaml
  args:
    - --mapping=2
    - --sequence=4
    - --offset=2
    - --width=120

- id: yamllint
  name: Format YAML code with yamllint
  description: Reformat YAML files according to the standard format.
  language: python
  entry: yamllint
  require_serial: false
  types:
    - yaml
  args:
    - --format=parsable
    - --strict

- id: yapf
  name: Format Python code with yapf
  description: Reformat Python code according to the standard format defined in .style.yapf.
  language: python
  entry: yapf
  require_serial: false
  types:
    - python
  args:
    - --in-place
    - --recursive
