---
# - id: circleci-config-validate
#   name: CircleCI config validation
#   description: Test if the CircleCI config is well formed.
#   entry: hooks/circleci-config-validate.sh
#   language: script
#   files: ^.circleci/config.yml$

# - id: go-test
#   name: go test
#   description: Runs `go test` and asserts no tests are failing.
#   entry: hooks/go-test.sh
#   language: script
#   files: \.go$

# - id: go-mod-tidy
#   name: go mod tidy
#   description: Runs `go mod tidy` to ensure `go.mod` matches the project source.
#   entry: hooks/go-mod-tidy.sh
#   language: script
#   files: \.go$

# - id: go-generate
#   name: go generate
#   description: Runs `go generate` against the projects go files.
#   entry: hooks/go-generate.sh
#   language: script
#   files: \.go$
#   always_run: true

# - id: forbid-binary
#   name: Forbid binaries
#   description: Forbid binary files from being committed
#   entry: hooks/forbid-binary.sh
#   language: script
#   types: ['binary']

- id: git-check
  name: Check for conflict markers and core.whitespace errors
  description: Use Git to check for conflict markers and core.whitespace errors, respecting .gitattributes.
  language: script
  entry: hooks/git-check.sh
  require_serial: false

- id: gofumpt
  name: Format Go code using gofumpt
  description: Reformat the Go code according to the standard format.
  language: script
  entry: hooks/gofumpt.sh
  require_serial: false
  files: \.go$
  args:
    - -w

- id: golangci-lint
  name: Statically analyze Go code using golangci-lint
  description: Statically analyze and lint Go code to catch potential errors.
  language: script
  entry: hooks/golangci-lint.sh
  require_serial: true

- id: gomodupdate
  name: Check go.mod for updates to any dependencies
  description: Check go.mod for updates to any dependencies.
  language: script
  entry: hooks/gomodupdate.sh
  require_serial: false
  args:
    - -update
    - -direct
    - -style=markdown

- id: go-consistent
  name: Check for consistent Go patterns in the code
  description: Check for consistent Go patterns in the code.
  language: script
  entry: hooks/go-consistent.sh
  require_serial: false

- id: goconst
  name: Check Go files for opportunities to turn strings into constants
  description: Check Go files for opportunities to turn strings into constants.
  language: script
  entry: hooks/goconst.sh
  require_serial: false

- id: markdownlint
  name: Statically analyze Markdown documents using markdownlint-cli
  description: Statically analyze Markdown documents using markdownlint-cli.
  language: script
  entry: hooks/markdownlint.sh
  require_serial: false
  files: \.(md|mdown|markdown)$
  exclude_types:
    - shell
  args:
    - --ignore
    - node_modules
    - --ignore
    - .github
    - --fix

- id: script-must-have-extension
  name: Shell script filename ends in .sh
  description: Verifies that shell script filenames ends in .sh.
  language: script
  entry: hooks/script_must_have_extension.sh
  types:
    - shell

- id: shellcheck
  name: Test shell scripts with ShellCheck
  description: Run ShellCheck over the file to identify poor practices or potential problems.
  language: script
  entry: hooks/shellcheck.sh
  require_serial: false
  types:
    - shell
  exclude_types:
    - csh
    - perl
    - python
    - ruby
    - tcsh
    - zsh
  args:
    - -e
    - SC1091

- id: shfmt
  name: Format shell scripts with shfmt
  description: Reformat the shell scripts according to the standard format.
  language: script
  entry: hooks/shfmt.sh
  require_serial: false
  types:
    - shell
  exclude_types:
    - csh
    - perl
    - python
    - ruby
    - tcsh
    - zsh
  args:
    - -s
    - -w
    - -ln=bash
    - -i=4
    - -ci
    - -sr

- id: yamlfmt
  name: Format YAML files
  description: Format YAML files
  entry: ./yamlfmt
  language: script
  types:
    - yaml
  args:
    - --mapping=2
    - --sequence=4
    - --offset=2
    - --width=120

- id: yamllint
  name: Format YAML code with yamllint
  description: Reformat YAML files according to the standard format.
  language: python
  entry: yamllint
  require_serial: false
  types:
    - yaml
  args:
    - --format=parsable
    - --strict

- id: yapf
  name: Format Python code with yapf
  description: Reformat Python code according to the standard format defined in .style.yapf.
  language: python
  entry: yapf
  require_serial: false
  types:
    - python
  args:
    - --in-place
    - --recursive
